const lngArr = {
  homepage: {
    pl: "Strona główna",
    ua: "Головна сторінка",
    en: "Homepage",
    ru: "Домашняя страница",
  },
  about: {
    pl: "O aplikacji",
    ua: "Про додаток",
    en: "About the application",
    ru: "О приложении",
  },
  "desc-banner": {
    pl: "Centrum informacji dla pracowników AUTODOC",
    ua: "Інформаційний центр для працівників AUTODOC",
    en: "AUTODOC employee information center",
    ru: "Информационный центр для сотрудников AUTODOC",
  },
  "hr-category": {
    pl: "Kadry",
    ua: "Кадри",
    en: "HR",
    ru: "Кадры",
  },
  "contacts-category": {
    pl: "Kontakty",
    ua: "Контакти",
    en: "Contacts",
    ru: "Контакты",
  },
  "regulations-category": {
    pl: "Regulaminy",
    ua: "Положення",
    en: "Regulations",
    ru: "Акты",
  },
  "assist-msg-index": {
    pl: "Wybierz kategorię",
    ua: "Оберіть категорію",
    en: "Choose a category",
    ru: "Выберите категорию",
  },
  "work-reg": {
    pl: "Regulamin pracy",
    ua: "Робочий регламент",
    en: "Work regulations",
    ru: "Рабочий регламент",
  },
  "bon-reg": {
    pl: "Regulamin premii",
    ua: "Регламент бонусу",
    en: "Bonus regulations",
    ru: "Регламент бонуса",
  },
  "add-wr": {
    pl: "Aneks do regulaminu pracy",
    ua: "Додаток до Регламенту",
    en: "Annex to work regulations",
    ru: "Приложение к Регламенту",
  },
  "loyalty-bonus": {
    pl: "Dodatek lojalnościowy",
    ua: "Додаток за лояльність",
    en: "Loyalty bonus",
    ru: "Надбавка за лояльность",
  },
  applications: {
    pl: "Wnioski",
    ua: "Заяви",
    en: "Applications",
    ru: "Заявления",
  },
  residence: {
    pl: "Karta pobytu",
    ua: "Посвідка на проживання",
    en: "Residence card",
    ru: "Вид на жительство",
  },
  "leave-requests": {
    pl: "Wnioski o urlop",
    ua: "Заяви про відпустку",
    en: "Vacation requests",
    ru: "Заявления на отпуск",
  },
  "personal-exit": {
    pl: "Wyjście prywatne",
    ua: "Приватний вихід",
    en: "Private exit",
    ru: "Частный выход",
  },
  "force-majeure": {
    pl: "Siła wyższa",
    ua: "Форс-мажор",
    en: "Force majeure",
    ru: "Форс-мажор",
  },
  "birthday-leave": {
    pl: "Urlop urodzinowy",
    ua: "Вихідний до дня народження",
    en: "Birthday leave",
    ru: "Выходной к дню рождения",
  },
  "caring-leave": {
    pl: "Urlop opiekuńczy",
    ua: "Відпустка для догляду",
    en: "Caregiving leave",
    ru: "Отпуск по уходу",
  },
  "vacation-cancellation": {
    pl: "Anulowanie urlopu",
    ua: "Скасування відпустки",
    en: "Vacation cancellation",
    ru: "Аннулирование отпуска",
  },
  "msg-shift-green": {
    pl: "Zmiana Green",
    ua: "Зміна Green",
    en: "Shift Green",
    ru: "Смена Green",
  },
  "msg-shift-orange": {
    pl: "Zmiana Orange",
    ua: "Зміна Orange",
    en: "Shift Orange",
    ru: "Смена Orange",
  },
  "msg-shift-m13-dark": {
    pl: "Zmiana M13 Dark",
    ua: "Зміна M13 Dark",
    en: "Shift M13 Dark",
    ru: "Смена M13 Dark",
  },
  "msg-shift-blue": {
    pl: "Zmiana Blue",
    ua: "Зміна Blue",
    en: "Shift Blue",
    ru: "Смена Blue",
  },
  "msg-shift-red": {
    pl: "Zmiana Red",
    ua: "Зміна Red",
    en: "Shift Red",
    ru: "Смена Red",
  },
  "msg-shift-brown": {
    pl: "Zmiana Brown",
    ua: "Зміна Brown",
    en: "Shift Brown",
    ru: "Смена Brown",
  },
  "msg-shift-yellow": {
    pl: "Zmiana Yellow",
    ua: "Зміна Yellow",
    en: "Shift Yellow",
    ru: "Смена Yellow",
  },
  "msg-shift-m26-dark": {
    pl: "Zmiana M26 Dark",
    ua: "Зміна M26 Dark",
    en: "Shift M26 Dark",
    ru: "Смена M26 Dark",
  },
};
