const lngArr = {
  homepage: {
    pl: "Strona główna",
    ua: "Головна сторінка",
    en: "Homepage",
    ru: "Домашняя страница",
  },
  about: {
    pl: "O aplikacji",
    ua: "Про додаток",
    en: "About the application",
    ru: "О приложении",
  },
  "desc-banner": {
    pl: "Centrum informacji dla pracowników AUTODOC",
    ua: "Інформаційний центр для працівників AUTODOC",
    en: "AUTODOC employee information center",
    ru: "Информационный центр для сотрудников AUTODOC",
  },
  "hr-category": {
    pl: "Kadry",
    ua: "Кадри",
    en: "HR",
    ru: "Кадры",
  },
  "contacts-category": {
    pl: "Kontakty",
    ua: "Контакти",
    en: "Contacts",
    ru: "Контакты",
  },
  "regulations-category": {
    pl: "Regulaminy",
    ua: "Положення",
    en: "Regulations",
    ru: "Акты",
  },
  "assist-msg-index": {
    pl: "Wybierz kategorię",
    ua: "Оберіть категорію",
    en: "Choose a category",
    ru: "Выберите категорию",
  },
  "work-reg": {
    pl: "Regulamin pracy",
    ua: "Робочий регламент",
    en: "Work regulations",
    ru: "Рабочий регламент",
  },
  "bon-reg": {
    pl: "Regulamin premii",
    ua: "Регламент бонусу",
    en: "Bonus regulations",
    ru: "Регламент бонуса",
  },
  "add-wr": {
    pl: "Aneks do regulaminu pracy",
    ua: "Додаток до Регламенту",
    en: "Annex to work regulations",
    ru: "Приложение к Регламенту",
  },
  "loyalty-bonus": {
    pl: "Dodatek lojalnościowy",
    ua: "Додаток за лояльність",
    en: "Loyalty bonus",
    ru: "Надбавка за лояльность",
  },
  applications: {
    pl: "Wnioski",
    ua: "Заяви",
    en: "Applications",
    ru: "Заявления",
  },
  residence: {
    pl: "Karta pobytu",
    ua: "Посвідка на проживання",
    en: "Residence card",
    ru: "Вид на жительство",
  },
  "instruction-button": {
    pl: `Instrukcja <svg id="hideArrowInstruction" class="toggle-arrow-icon" width="28" height="28"><use href="../../../images/svg-group.svg#icon-hide-arrow"></use></svg>`,
    ua: `Інструкція <svg id="hideArrowInstruction" class="toggle-arrow-icon" width="28" height="28"><use href="../../../images/svg-group.svg#icon-hide-arrow"></use></svg>`,
    en: `Instruction <svg id="hideArrowInstruction" class="toggle-arrow-icon" width="28" height="28"><use href="../../../images/svg-group.svg#icon-hide-arrow"></use></svg>`,
    ru: `Инструкция <svg id="hideArrowInstruction" class="toggle-arrow-icon" width="28" height="28"><use href="../../../images/svg-group.svg#icon-hide-arrow"></use></svg>`,
  },
  "annual-leave": {
    pl: "Urlop wypoczynkowy",
    ua: "Щорічна відпустка",
    en: "Annual leave",
    ru: "Ежегодный отпуск",
  },
  "request-leave": {
    pl: "Urlop na żądanie",
    ua: "Відпустка за вимогою",
    en: "Request leave",
    ru: "Отпуск по требованию",
  },
  "unpaid-leave": {
    pl: "Urlop bezpłatny",
    ua: "Неоплачувана відпустка",
    en: "Unpaid leave",
    ru: "Отпуск за свой счёт",
  },
  "special-leave": {
    pl: "Urlop okolicz nościowy",
    ua: "Відпустка за особливих обставин",
    en: "Special leave",
    ru: "Отпуск по особому случаю",
  },
  "childcare-leave": {
    pl: "Opieka nad dzieckiem",
    ua: "Відпустка по догляду за дитиною",
    en: "Childcare leave",
    ru: "Отпуск по уходу за ребёнком",
  },
  "leave-requests": {
    pl: "Wnioski o urlop",
    ua: "Заяви про відпустку",
    en: "Vacation requests",
    ru: "Заявления на отпуск",
  },
  "personal-exit": {
    pl: "Wyjście prywatne",
    ua: "Відгул за особистими обставинами",
    en: "Private leave",
    ru: "Отгул по личным обстоятельствам",
  },
  "force-majeure": {
    pl: "Siła wyższa",
    ua: "Форс-мажор",
    en: "Force majeure",
    ru: "Форс-мажор",
  },
  "birthday-leave": {
    pl: "Urlop urodzinowy",
    ua: "Відпустка до дня народження",
    en: "Birthday leave",
    ru: "Отпуск ко дню рождения",
  },
  "caring-leave": {
    pl: "Urlop opiekuńczy",
    ua: "Відпустка по догляду",
    en: "Carer's leave",
    ru: "Отпуск по уходу",
  },
  "vacation-cancellation": {
    pl: "Anulowanie urlopu",
    ua: "Скасування відпустки",
    en: "Vacation cancellation",
    ru: "Аннулирование отпуска",
  },
  "msg-shift-green": {
    pl: "Zmiana Green",
    ua: "Зміна Green",
    en: "Shift Green",
    ru: "Смена Green",
  },
  "msg-shift-orange": {
    pl: "Zmiana Orange",
    ua: "Зміна Orange",
    en: "Shift Orange",
    ru: "Смена Orange",
  },
  "msg-shift-m13-dark": {
    pl: "Zmiana M13 Dark",
    ua: "Зміна M13 Dark",
    en: "Shift M13 Dark",
    ru: "Смена M13 Dark",
  },
  "msg-shift-blue": {
    pl: "Zmiana Blue",
    ua: "Зміна Blue",
    en: "Shift Blue",
    ru: "Смена Blue",
  },
  "msg-shift-red": {
    pl: "Zmiana Red",
    ua: "Зміна Red",
    en: "Shift Red",
    ru: "Смена Red",
  },
  "msg-shift-brown": {
    pl: "Zmiana Brown",
    ua: "Зміна Brown",
    en: "Shift Brown",
    ru: "Смена Brown",
  },
  "msg-shift-yellow": {
    pl: "Zmiana Yellow",
    ua: "Зміна Yellow",
    en: "Shift Yellow",
    ru: "Смена Yellow",
  },
  "msg-shift-m26-dark": {
    pl: "Zmiana M26 Dark",
    ua: "Зміна M26 Dark",
    en: "Shift M26 Dark",
    ru: "Смена M26 Dark",
  },
  "annual-leave-desc-1": {
    pl: "Każdemu pracownikowi zatrudnionemu bezpośrednio przez AUTODOC Logistics należy się 26 dni urlopu wypoczynkowego, który nalicza się 1 stycznia każdego roku i przysługuje do 31 grudnia danego roku. Pracownikom agencyjnym nalicza się 2 dni urlopu wypoczynkowego każadego kolejnego miesiąca od daty zatrudnienia wskazanej w umowie o prace.",
    ua: "Кожен працівник, який працює безпосередньо на AUTODOC Logistics, має право на 26 днів щорічної відпустки, яка нараховується 1 січня кожного року і триває до 31 грудня цього року. Працівникам агентства нараховується 2 дні щорічної відпустки кожного місяця поспіль з дня працевлаштування, зазначеного в трудовому договорі.",
    en: "Every employee directly employed by AUTODOC Logistics is entitled to 26 days of annual leave, which accrues on 1 January each year and is due until 31 December of that year. Agency workers are credited with 2 days of annual leave each consecutive month from the date of employment indicated in the employment contract.",
    ru: "Если работник, трудоустроенный через агентство, устраивается напрямую в AUTODOC Logistics, то ежегодный отпуск начисляется пропорционально за оставшиеся месяцы года.",
  },
  "annual-leave-desc-2": {
    pl: "Jeżeli pracownik agencyjny przechodzi na bezpośrednie zatrudnienie do AUTODOC Logistics wtedy urlop wypoczynkowy nalicza mu się proporcjonalnie na pozostałe do końca roku miesiące.",
    ua: "Якщо співробітник агентства переходить на пряме працевлаштування в AUTODOC Logistics, то щорічна відпустка нараховується пропорційно за решту місяців року.",
    en: "If an agency worker switches to direct employment with AUTODOC Logistics then annual leave is accrued pro rata for the remaining months of the year.",
    ru: "Если работник, трудоустроенный через агентство, устраивается напрямую в AUTODOC Logistics, то ежегодный отпуск начисляется пропорционально за оставшиеся месяцы года.",
  },
  "annual-leave-desc-3": {
    pl: "Przed wypisaniem wniosku obowiązkowo skonsultuj się z liderem swojego działu, czy wyraża zgodę na urlop w wybranym przez Ciebie terminie.",
    ua: "Обов'язково проконсультуйтесь з керівником вашого відділу щодо обраних вами дат, перш ніж писати заяву про надання відпустки.",
    en: "It is mandatory to consult with your department leader before writing out the request as to whether the leader agrees to leave on the date of your choice.",
    ru: "Прежде чем подавать заявление, обязательно проконсультируйтесь с руководителем своего отдела по поводу предложенных вами дат отпуска.",
  },
  "annual-leave-step-1": {
    pl: "Wypełnij pole z datą złożenia wniosku. Należy wpisać datę w którą wniosek został złożony. Urlop wypoczynkowy jest urlopem planowanym, więc data powinna być przed jego rozpoczęciem.",
    ua: "Заповніть поле з датою подачі заяви. Необхідно вказати день, коли заява подається. Щорічна відпустка — це запланована відпустка, тому дата заяви повинна передувати даті її початку.",
    en: "Fill in the field with the date of request. You should write the date on which the request was submitted. Annual leave is planned leave, so the date should be before it starts.",
    ru: "Заполните поле даты подачи заявления. Укажите дату подачи заявления. Ежегодный отпуск — это запланированный отпуск, поэтому дата подачи заявления должна быть до его начала.",
  },
  "annual-leave-step-type": {
    pl: "Zaznacz w odpowiednim polu jaki typ urlopu Ciebie interesuje. W tym przypadku zaznacz «Wypoczynkowego».",
    ua: "Зазначте у відповідному полі, який тип відпустки вас цікавить. У даному випадку зазначте «Wypoczynkowego».",
    en: "Mark in the appropriate field which type of leave you are interested in. In this case, mark «Wypoczynkowego».",
    ru: "Отметьте в соответствующем поле нужный вам тип отпуска. В данном случае отметьте «Wypoczynkowego».",
  },
  "request-leave-desc-1": {
    pl: "Każdemu pracownikowi zatrudnionemu na umowę o pracę należą się 4 dni urlopu na żądanie w ciągu roku.",
    ua: "Кожен співробітник, який працює на основі трудового договору, має право на 4 дні відпустки за вимогою на рік.",
    en: "Every employee with an employment contract is entitled to 4 days of leave on demand per year.",
    ru: "Каждый сотрудник, работающий на основе трудового договора, имеет право на 4 дня отпуска по требованию в год.",
  },
  "request-leave-desc-2": {
    pl: "Urlop na żądanie zgłasza się do bezpośredniego przełożonego lub do działu HR przed rozpoczęciem pracy. Wniosek wypisz najpóźniej pierwszego dnia po powrocie do pracy po wykorzystaniu urlopu na żądanie.",
    ua: "Про відпустку за вимогою необхідно повідомити безпосереднього керівника або відділ кадрів до початку роботи. Заява подається не пізніше першого дня виходу на роботу після відпустки за вимогою.",
    en: "Leave on demand shall be reported to the direct manager or the HR department before starting work. The request must be written out no later than the first day after returning to work after taking the leave on demand.",
    ru: " Об отпуске по требованию следует сообщить непосредственному руководителю или в отдел кадров до начала работы. Заявление должно быть подано не позднее первого дня возвращения на работу после использования отпуска по требованию.",
  },
  "request-leave-desc-3": {
    pl: "Urlop na żądanie pomniejsza pulę urlopu wypoczynkowego.",
    ua: "Відпустка за вимогою надається за рахунок щорічної відпустки.",
    en: "Leave on demand reduces the annual leave pool.",
    ru: "Отпуск по требованию назначается за счёт ежегодного отпуска.",
  },
  "request-leave-step-type": {
    pl: "Zaznacz w odpowiednim polu jaki typ urlopu Ciebie interesuje. W tym przypadku zaznacz «Na żądanie».",
    ua: "Зазначте у відповідному полі, який тип відпустки вас цікавить. У даному випадку зазначте «Na żądanie».",
    en: "Mark in the appropriate field which type of leave you are interested in. In this case, mark «Na żądanie».",
    ru: "Отметьте в соответствующем поле нужный вам тип отпуска. В данном случае отметьте «Na żądanie».",
  },
  "request-leave-step-from": {
    pl: "Wpisz datę w której zgłaszałeś urlop na żądanie.",
    ua: "Вкажіть дату повідомлення про відпустку за вимогою.",
    en: "Write the date on which you requested leave on demand.",
    ru: "Укажите дату, когда вы сообщили об отпуске по требованию.",
  },
  "unpaid-leave-desc-1": {
    pl: "Każdy pracownik zatrudniony na umowę o pracę może zawnioskować o urlop bezpłatny. Wykorzystać go można dopiero po uprzednim wykorzystaniu całej puli urlopu wypoczynkowego.",
    ua: "Кожен співробітник, який працює на підставі трудового договору, має право попросити відпустку без збереження заробітної плати. Її можна взяти лише після того, як буде використано весь ліміт днів оплачуваної відпустки.",
    en: "Every employee with an employment contract may request unpaid leave. It can only be taken once the entire annual leave pool has been used.",
    ru: "Каждый сотрудник, работающий на основе трудового договора, может запросить отпуск без сохранения заработной платы. Его можно использовать только после использования всех отпускных дней.",
  },
  "unpaid-leave-desc-2": {
    pl: "Na urlop bezpłatny zgodę udziela bezpośredni przełożony.",
    ua: "Відпустка без збереження заробітної плати затверджується безпосереднім керівником.",
    en: "Unpaid leave is authorised by the direct manager.",
    ru: "Неоплачиваемый отпуск утверждается непосредственным руководителем.",
  },
  "unpaid-leave-desc-3": {
    pl: "Za urlop bezpłatny nie przysługuje wynagrodzenie. Zwolnienie lekarskie podczas wykorzystywania urlopu bezpłatnego jest także niepłatne.",
    ua: "Компенсація за неоплачувану відпустку не виплачується. Лікарняний під час неоплачуваної відпустки також не підлягає оплаті.",
    en: "No remuneration is payable for unpaid leave. Sick leave while taking unpaid leave is also unpaid.",
    ru: "За неоплачиваемый отпуск вознаграждение не выплачивается. Больничный во время неоплачиваемого отпуска также не оплачивается.",
  },
  "unpaid-leave-step-type": {
    pl: "Zaznacz w odpowiednim polu jaki typ urlopu Ciebie interesuje. W tym przypadku zaznacz «Bezpłatnego».",
    ua: "Зазначте у відповідному полі, який тип відпустки вас цікавить. У даному випадку зазначте «Bezpłatnego».",
    en: "Mark in the appropriate field which type of leave you are interested in. In this case, mark «Bezpłatnego».",
    ru: "Отметьте в соответствующем поле нужный вам тип отпуска. В данном случае отметьте «Bezpłatnego».",
  },
  "special-leave-desc-1": {
    pl: "Każdy pracownik zatrudniony na umowę o pracę może zawnioskować o urlop okolicznościowy. W zależności od okoliczności pracownikowi należy się:",
    ua: "Кожен співробітник, який працює на підставі трудового договору, має право подати заяву на відпустку за особливих обставин. Залежно від обставин працівник має право на:",
    en: "Every employee with an employment contract may apply for special leave. Depending on the circumstances, the employee is entitled to:",
    ru: "Каждый сотрудник, работающий на основе трудового договора, может запросить отпуск по особому случаю. В зависимости от обстоятельств работник имеет право:",
  },
  "special-leave-desc-2": {
    pl: "2 dni urlopu okolicznościowego - w razie ślubu pracownika lub urodzenia się jego dziecka albo zgonu i pogrzebu małżonka pracownika lub jego dziecka, ojca, matki, ojczyma lub macochy;",
    ua: "2 дні спеціальної відпустки — у разі весілля працівника або народження дитини працівника, або смерті та похорону чоловіка/дружини чи дитини працівника, батька, матері, вітчима чи мачухи;",
    en: "2 days of special leave - in the event of the employee's wedding or the birth of employee's child, or the death and funeral of the employee's spouse or child, father, mother, stepfather or stepmother;",
    ru: "2 дня отпуска по случаю свадьбы, рождения ребенка, смерти и похорон супруга, ребенка, отца, матери, отчима или мачехи;",
  },
  "special-leave-desc-3": {
    pl: "1 dzień urlopu okolicznościowego - w razie ślubu dziecka pracownika albo zgonu i pogrzebu jego siostry, brata, teściowej, teścia, babki, dziadka, a także innej osoby pozostającej na utrzymaniu pracownika lub pod jego bezpośrednią opieką;",
    ua: "1 день спеціальної відпустки — у разі весілля дитини працівника або смерті та похорону сестри, брата, свекрухи, свекра, бабусі, дідуся або будь-якої іншої особи, яка перебуває на утриманні працівника або під безпосереднім доглядом працівника;",
    en: "1 day of special leave - in the event of the wedding of the employee's child or the death and funeral of the employee's sister, brother, mother-in-law, father-in-law, grandmother, grandfather, or any other person dependent on the employee or under the employee's direct care;",
    ru: "1 день отпуска по случаю свадьбы ребенка, смерти и похорон сестры, брата, свекрови, свекра, бабушки, дедушки или любого лица, находящегося на иждивении работника или под непосредственной опекой работника.",
  },
  "special-leave-desc-4": {
    pl: "Urlop okolicznościowy można wykorzystać w terminie zbliżonym do wydarzenia, które wystąpiło.",
    ua: "Відпустку за особливих обставин можна отримати в дату, близьку до події, що сталася.",
    en: "Special leave can be taken on a date close to the event that occurred.",
    ru: "Работник может взять отпуск по особому случаю в дату, близкую к событию.",
  },
  "special-leave-step-type": {
    pl: "Zaznacz w odpowiednim polu jaki typ urlopu Ciebie interesuje. W tym przypadku zaznacz «Okolicznościowego».",
    ua: "Зазначте у відповідному полі, який тип відпустки вас цікавить. У даному випадку зазначте «Okolicznościowego».",
    en: "Mark in the appropriate field which type of leave you are interested in. In this case, mark «Okolicznościowego».",
    ru: "Отметьте в соответствующем поле нужный вам тип отпуска. В данном случае отметьте «Okolicznościowego».",
  },
  "special-leave-step-reason": {
    pl: "Napisz na jaką okoliczność wnioskujesz o urlop okolicznościowy.",
    ua: "Вкажіть за яких обставин ви просите про спеціальну відпустку.",
    en: "Write for which circumstance you are requesting special leave.",
    ru: "Укажите, по какому случаю вы запрашиваете отпуск.",
  },
  "special-leave-step-days": {
    pl: "Wpisz ilość roboczych dni 1 lub 2. Nie wliczaj dni wolnych od pracy.",
    ua: "Вкажіть кількість робочих днів: 1 або 2. Не враховуйте вихідні дні.",
    en: "Write the number of working days: 1 or 2. Do not include holidays.",
    ru: "Напишите количество рабочих дней, в которые вы будете отсутствовать (1 или 2). Не учитывайте выходные дни.",
  },
  "childcare-leave-desc-1": {
    pl: "Każdy pracownik zatrudniony na umowę o pracę i opiekujący się dzieckiem do lat 14 może zawnioskować o urlop z tytułu opieki nad dzieckiem.",
    ua: "Кожен співробітник, який працює в компанії на підставі трудового договору та доглядає за дитиною до 14 років, може подати заяву на відпустку по догляду за дитиною.",
    en: "Every employee with an employment contract and caring for a child under 14 years of age can apply for childcare leave.",
    ru: "Каждый сотрудник, работающий на основе трудового договора и ухаживающий за ребенком до 14 лет, может подать заявление на отпуск по уходу за ребёнком.",
  },
  "childcare-leave-desc-2": {
    pl: "W ciągu roku przysługują dwa dni takiego urlopu obojgu rodzicom. Jeżeli jeden z rodziców dziecka już wykorzystał ten urlop u swojego pracodawcy, drugi nie może o niego wnioskować",
    ua: "Обоє батьків мають право на два дні такої відпустки на рік. Якщо один/на з батьків дитини вже взяв/ла відпустку у свого роботодавця,  другий/а з батьків не може подати заяву на її отримання.",
    en: "Both parents are entitled to two days of such leave per year. If one of the child's parents has already taken the leave with their employer, the other parent cannot apply for it.",
    ru: "Оба родителя имеют право на два дня такого отпуска в год. Если один из родителей ребенка уже взял отпуск у своего работодателя, другой родитель не может на него претендовать.",
  },
  "childcare-leave-desc-3": {
    pl: "Przysługujące pracownikowi 2 dni można również rozbić na godziny. Wówczas przysługuje 16h na rok.",
    ua: "2 дні, на які мають право співробітники, також можуть бути розбиті на години. В такому випадку працівник має право на 16 годин на рік.",
    en: "The 2 days to which the employee is entitled can also be broken down into hours. The employee is then entitled to 16 hours per year.",
    ru: "2 дня также могут быть разбиты на часы. Работник имеет право на 16 часов отпуска по уходу за ребенком в год.",
  },
  "childcare-leave-step-type": {
    pl: "Zaznacz w odpowiednim polu jaki typ urlopu Ciebie interesuje. W tym przypadku zaznacz «Z tytułu opieki nad dzieckiem».",
    ua: "Зазначте у відповідному полі, який тип відпустки вас цікавить. У даному випадку зазначте «Z tytułu opieki nad dzieckiem».",
    en: "Mark in the appropriate field which type of leave you are interested in. In this case, mark «Z tytułu opieki nad dzieckiem».",
    ru: "Отметьте в соответствующем поле нужный вам тип отпуска. В данном случае отметьте «Z tytułu opieki nad dzieckiem».",
  },
  "childcare-leave-step-birthday": {
    pl: "Wpisz datę urodzenia dziecka.",
    ua: "Вкажіть дату народження вашої дитини.",
    en: "Write the date of birth of your child.",
    ru: "Укажите дату рождения вашего ребенка. ",
  },
  "childcare-leave-step-date-to": {
    pl: "Wpisz datę, kiedy skończy się twój urlop. Należy wpisać ostatni dzień, kiedy jeszcze będziesz przybywać na urlopie. Jeżeli wybrałeś opcję rozbicia tego urlopu na godziny wpisz dzień wykorzystywania i ilość godzin «od … do …».",
    ua: "Вкажіть дату закінчення відпустки. Це повинен бути останній день, коли ви все ще будете перебувати у відпустці. Якщо ви вирішили розбити цю відпустку на години, введіть день використання та кількість годин «від … до …».",
    en: "Write the date when your leave will end. You should write the last day you will still be on leave. If you have chosen to break this leave into hours enter the day of use and the number of hours «from … to …».",
    ru: "Укажите дату окончания отпуска. Это должен быть последний день, когда вы все еще будете пребывать в отпуске.  Если вы решили разбить этот отпуск на часы, укажите день использования отпуска и количество часов «с … по …».",
  },
  "childcare-leave-step-days": {
    pl: "Wpisz ilość dni roboczych: 1 lub 2 (lub ilość godzin). Nie wliczaj dni wolnych od pracy.",
    ua: "Вкажіть кількість робочих днів: 1 або 2 (або кількість годин). Не враховуйте вихідні дні.",
    en: "Write the number of working days: 1 or 2 (or the number of hours). Do not include holidays.",
    ru: "Напишите количество рабочих дней, в которые вы будете отсутствовать: 1 или 2 (или количество часов). Не учитывайте выходные дни.",
  },
  "private-leave": {
    pl: "Wniosek o wyrażenie zgody na wyjście prywatne",
    ua: "Заява про надання відгулу за особистими обставинами",
    en: "Request for permission for private leave",
    ru: "Заявление о предоставлении отгула по личным обстоятельствам",
  },
  "private-leave-desc-1": {
    pl: "Wniosek ten należy wypisać, jeżeli w trakcie wykonywania twojej pracy musisz opuścić stanowisko pracy i wyjść z magazynu. Obowiązkowo trzeba uzyskać zgodę bezpośredniego przełożonego na opuszczenie miejsca pracy przed zakończeniem zmiany.",
    ua: "Таку заяву необхідно заповнити у випадку, якщо під час роботи вам необхідно залишити своє робоче місце і вийти зі складу. Працівник повинен обов'язково отримати дозвіл безпосереднього керівника, якщо йому потрібно залишити робоче місце до закінчення зміни.",
    en: "This request must be written out if, in the course of your work, you have to leave your workplace and leave the warehouse. It is mandatory to obtain permission from the direct manager to leave the workplace before the end of the shift.",
    ru: "Это заявление подается, если во время работы вам нужно покинуть свое рабочее место и уйти со склада. В случае необходимости покинуть рабочее место до окончания смены вы должны получить разрешение непосредственного руководителя.",
  },
  "private-leave-desc-2": {
    pl: "Wyjście prywatne wypisujemy na pełne godziny pracy. Wniosku nie można wypisać na cały dzień pracy.",
    ua: "Відгул за особистими обставинами виписується на повні робочі години. Працівник не може подати заяву на повний робочий день.",
    en: "Private leave is written out for full working hours. The request cannot be written out for a full working day.",
    ru: "Отпуск по личным обстоятельствам оформляется на полные рабочие часы. Работник не может подать заявление на отпуск на полный рабочий день.",
  },
  "private-leave-desc-3": {
    pl: "Brakujące godziny zostają ściągnięte z Twoich pierwszych nadgodzin, które wystąpiły w danym miesiącu.",
    ua: "Години відсутності будуть зняті з вашої першої понаднормової зміни протягом місяця.",
    en: "The missing hours are taken off your first overtime that occurred in the month.",
    ru: "Часы отсутствия снимаются с вашей первой сверхурочной смены в текущем месяце.",
  },
  "private-leave-step-date": {
    pl: "Wpisz datę – w jaki dzień wnioskujesz o wyjście prywatne.",
    ua: "Напишіть дату — в який день ви хочете отримати відгул за особистими обставинами.",
    en: "Write the date - what day you are requesting private leave.",
    ru: "Укажите дату, когда вы хотите получить отгул по личным обстоятельствам.",
  },
  "private-leave-step-from": {
    pl: "Wpisz godziny w jakich chcesz wyjść i nie będzie Ciebie w pracy.",
    ua: "Впишіть час, на який ви хочете піти, і вас не буде на роботі.",
    en: "Write the time you want to leave and you will be out of work.",
    ru: "Впишите время, на которое вы хотите уйти, и вас не будет на работе.",
  },
  "force-leave": {
    pl: "Wniosek o udzielenie wolnego z powodu dzałania syły wyższej",
    ua: "Заява на відгул у зв'язку з форс-мажорними обставинами",
    en: "Request for leave due to force majeure",
    ru: "Заявление на отгул в связи с форс-мажорными обстоятельствами",
  },
  "force-leave-desc-1": {
    pl: "Wniosek ten należy wypisać, jeżeli w trakcie wykonywania twojej pracy musisz opuścić stanowisko pracy i wyjść z magazynu, gdyż wydarzyło się coś niespodziewanego.",
    ua: "Така заява подається у випадку, якщо під час роботи вам доведеться залишити своє робоче місце і вийти зі складу через непередбачувані обставини.",
    en: "This request should be written out if, in the course of your work, you have to leave your workplace and leave the warehouse because something unexpected has happened.",
    ru: "Это заявление подается, если в ходе вашей работы вы должны покинуть свое рабочее место и уйти со склада, в связи с непревиденными обстоятельствами.",
  },
  "force-leave-desc-2": {
    pl: "Każdy pracownik zatrudniony na umowę o pracę może wykorzystać w roku kalendarzowym wymiar 2 dni. Można również rozbić te dni na godziny – wówczas przysługuje 16h. Wniosek o udzielenie wolnego z powodu działania siły wyższej wypisujemy na pełne godziny.",
    ua: "Кожен співробітник, який працює на підставі трудового договору, може використати до 2-х днів відгулу у зв'язку з форс-мажорними обставинами у календарному році. Також можна розбити ці дні на години — в такому випадку нараховується 16 годин. Заява на відгул у зв'язку з форс-мажорними обставинами виписується в повних годинах.",
    en: "Each employee with a contract of employment can take up to 2 days in a calendar year. It is also possible to break these days down into hours - in which case 16 hours are entitled. A request for force majeure leave is written out in full hours.",
    ru: "Каждый сотрудник, работающий на основе трудового договора, может взять до 2 дней отгула в связи с форс-мажорными обстоятельствами в календарном году. Эти дни также можно разбить на часы. В этом случае предоставляется 16 часов. Заявление на отпуск в связи с форс-мажорным обстоятельствам подается на полные рабочие часы.",
  },
  "force-leave-desc-3": {
    pl: "Wolne z powodu działania siły wyższej płatne jest 50% Twojego wynagrodzenia.",
    ua: "Час відгулу у зв'язку з форс-мажорними обставинами оплачується в розмірі 50% від окладу.",
    en: "Force majeure leave is paid at 50% of your salary.",
    ru: "Время отгула в связи с форс-мажорными обстоятельствами оплачивается в размере 50% от оклада.",
  },
  "force-leave-step-date": {
    pl: "Wpisz datę – w jaki dzień wnioskujesz o „siłę wyższą”. Jeżeli wnioskujesz na godziny – datę i godziny.",
    ua: "Напишіть дату — день, коли вам потрібен відгул у зв'язку з форс-мажорними обставинами. Якщо вам потрібен відгул на декілька годин — вкажіть дату та години.",
    en: "Write the date - what day you are requesting “force majeure”. If you are requesting hours - the date and hours.",
    ru: "Укажите дату, когда вы будете отсутствовать в связи с форс-мажорными обстоятельствами. Если вы подаете заявление на определенные часы — укажите дату и часы.",
  },
  "force-leave-step-time": {
    pl: "Wpisz na ile dni lub godzin roboczych łącznie wypisałeś/wypisałaś wniosek.",
    ua: "Вкажіть, на скільки днів або робочих годин загалом ви написали заявку.",
    en: "Enter for how many days or working hours in total you wrote out the application.",
    ru: "Укажите, на сколько дней или рабочих часов в общей сложности вы написали заявление.",
  },
  "birthday-leave-title": {
    pl: "Wniosek o urlop urodzinowy",
    ua: "Заява на отримання відпустки до дня народження",
    en: "Request for birthday leave",
    ru: "Заявление на отпуск по случаю дня рождения",
  },
  "birthday-leave-desc-1": {
    pl: "Każdemu pracownikowi zatrudnionemu w ATDL bezpośrednio i przez agencje przysługuje jeden dzień urlopu urodzinowego.",
    ua: "Кожен співробітник, який працює в ATDL безпосередньо або через агентства, має право на один день відпустки до дня народження.",
    en: "Each employee working for ATDL directly and through agencies is entitled to one day of birthday leave.",
    ru: "Каждый сотрудник, работающий в ATDL напрямую и через агентства, имеет право на один день отпуска по случаю дня рождения.",
  },
  "birthday-leave-desc-2": {
    pl: "Urlop ten można wykorzystać maksymalnie do 4 tygodni po dacie urodzin.",
    ua: "Цю відпустку можна використати максимум протягом 4 тижнів після дня народження.",
    en: "This leave can be taken up to a maximum of 4 weeks after the birthday.",
    ru: "Этот отпуск можно взять максимум через 4 недели после дня рождения.",
  },
  "birthday-leave-desc-3": {
    pl: "Wniosku nie można wykorzystać przed datą urodzin.",
    ua: "Не можна скористатися відпусткою до дня дати народження.",
    en: "The request cannot be used before the birthday date.",
    ru: "Отпуск не может быть использован до дня даты рождения.",
  },
  "birthday-leave-step-date": {
    pl: "Wpisz datę - dzień w którym będziesz wykorzystywał urlop urodzinowy.",
    ua: "Напишіть дату — день запланованого відгулу до дня народження.",
    en: "Write the date - the day on which you will be taking your birthday leave.",
    ru: "Укажите день, на который вы берете отпуск по случаю дня рождения.",
  },
  "birthday-leave-step-bd": {
    pl: "Wpisz datę swoich urodzin.",
    ua: "Вкажіть свою дату народження.",
    en: "Write the date of your birthday.",
    ru: "Укажите дату своего дня рождения.",
  },
  "carers-leave": {
    pl: "Wniosek o urlop opiekuńczy",
    ua: "Заява про надання відпустки по догляду",
    en: "Request for carer’s leave",
    ru: "Заявление о предоставлении отпуска по уходу",
  },
  "carers-leave-desc-1": {
    pl: "Wniosek o urlop opiekuńczy można wykorzystać, jeżeli masz potrzebę zaopiekowania się członkiem rodziny, który mieszka z tobą.",
    ua: "Ви маєте право подати заяву на відпустку по догляду, якщо вам потрібно доглядати за членом сім'ї, який проживає з вами.",
    en: "You can request carer’s leave if you have a need to care for a family member who lives with you.",
    ru: "Вы можете подать заявление на отпуск по уходу, если вам необходимо ухаживать за членом семьи, который проживает с вами.",
  },
  "carers-leave-desc-2": {
    pl: "W ciągu roku można wykorzystać 5 dni urlopu opiekuńczego. Jest on niepłatny.",
    ua: "Ви можете отримати 5 днів такої відпустки на рік. Відпустка по догляду є не оплачуваною.",
    en: "You can take 5 days of carer’s leave per year. It is unpaid.",
    ru: "Вы можете взять 5 дней отпуска по уходу в год. Этот вид отпуска не оплачивается.",
  },
  "carers-leave-step-relname": {
    pl: "Wpisz imię i nazwisko osoby, którą będziesz się opiekować.",
    ua: "Напишіть ім'я та прізвище людини, за якою ви будете доглядати.",
    en: "Write the full name of the person you will be caring for.",
    ru: "Напишите имя и фамилию человека, за которым вы будете ухаживать.",
  },
  "carers-leave-step-relative": {
    pl: "Zaznacz stopień pokrewieństwa - kim dla Ciebie jest osoba, którą będziesz się opiekować.",
    ua: "Позначте ступінь відносин — ким для вас є людина, за якою ви будете доглядати.",
    en: "Mark the degree of relationship - who the person you will be caring for is to you.",
    ru: "Укажите степень родства — кем является для вас человек, за которым вы будете ухаживать.",
  },
  "carers-leave-step-adress": {
    pl: "Wpisz adres osoby którą będziesz się opiekować - musi to być ten sam adres pod którym mieszkasz.",
    ua: "Вкажіть адресу людини, за якою ви будете доглядати — це має бути та сама адреса, де ви проживаєте.",
    en: "Write the address of the person you will be caring for - it must be the same address where you live.",
    ru: "Укажите адрес человека, за которым вы будете ухаживать — это должен быть тот же адрес, по которому вы проживаете.",
  },
  "cancel-leave": {
    pl: "Wniosek o anulowanie urlopu",
    ua: "Заява про скасування відпустки",
    en: "Request for cancellation of leave",
    ru: "Заявление на аннулирование отпуска",
  },
  "cancel-leave-desc": {
    pl: "Wniosek o anulowanie urlopu musisz wypisać jeżeli wcześniej wypisałeś wniosek o urlop a teraz chcesz z tego urlopu zrezygnować.",
    ua: "Якщо ви раніше написали заяву про надання відпустки і тепер бажаєте її скасувати, вам необхідно написати заяву про скасування відпустки.",
    en: "You must write out a request for cancellation of leave if you have previously written out a request for leave and now wish to cancel that leave.",
    ru: "Вы должны написать заявление на аннулирование отпуска, если вы ранее запросили отпуск и теперь желаете его отменить.",
  },
  "cancel-leave-step-date": {
    pl: `Wpisz datę lub daty «od dnia - do dnia» w jakie dni chcesz anulować urlop.`,
    ua: "Вкажіть дату чи дати «від - до», на які ви бажаєте скасувати відпустку.",
    en: "Write the date or dates «from - to» on which days you wish to cancel the leave.",
    ru: "Укажите дату или даты «от - до» отпуска, который вы хотите отменить.",
  },
  "cancel-leave-step-count": {
    pl: "Wpisz z ilu łącznie dni urlopu rezygnujesz.",
    ua: "Вкажіть загальну кількість днів відпустки, яку ви хочете скасувати.",
    en: "Write how many total days of leave you are cancelling.",
    ru: "Укажите общее количество дней отпуска, которое вы хотите аннулировать.",
  },
  "leave-step-date": {
    pl: "Wypełnij pole z datą złożenia wniosku. Należy wpisać datę w którą wniosek został złożony.",
    ua: "Заповніть поле з датою подачі заяви. Необхідно вказати день, коли заява подається.",
    en: "Fill in the field with the date of request. You should write the date on which the request was submitted.",
    ru: "Заполните поле даты подачи заявления. Укажите дату подачи заявления.",
  },
  "leave-step-name": {
    pl: "Wpisz swoje imię i nazwisko czytelnie - łacińskimi literami w odpowiednim polu zaznaczonym na ilustracji.",
    ua: "Розбірливо напишіть своє ім'я латинськими літерами у відповідному полі, позначеному на ілюстрації.",
    en: "Write your full name legibly - in Latin letters - in the appropriate field marked in the illustration.",
    ru: "Напишите свое имя разборчиво латинскими буквами в соответствующем поле, отмеченном на иллюстрации.",
  },
  "leave-step-id": {
    pl: "Wpisz swój numer ID następnie wpisz nazwę działu.",
    ua: "Вкажіть свій номер ID та назву відділу.",
    en: "Write your ID number and then the name of the department.",
    ru: "Укажите свой ID и название отдела.",
  },
  "leave-step-employer": {
    pl: "Zaznacz w odpowiednim polu przez jakiego pracodawcę obecnie pracujesz.",
    ua: "У відповідному полі зазначте через якого роботодавця ви зараз працюєте.",
    en: "Mark in the appropriate field through which employer you currently work.",
    ru: "Отметьте в соответствующем поле, через какого работодателя вы в настоящее время работаете.",
  },
  "leave-step-shift": {
    pl: "Zaznacz w odpowiednim polu na której zmianie pracujesz.",
    ua: "Зазначте у відповідному полі на якій зміні ви працюєте.",
    en: "Mark in the appropriate field which shift you work.",
    ru: "Отметьте в соответствующем поле, на какой смене вы работаете.",
  },
  "leave-step-date-from": {
    pl: "Wpisz datę od której będzie się zaczynać twój urlop.",
    ua: "Вкажіть дату, з якої почнеться ваша відпустка.",
    en: "Write the date from which your leave will start.",
    ru: "Напишите дату, с которой начнется ваш отпуск.",
  },
  "leave-step-date-to": {
    pl: "Wpisz datę, kiedy skończy się twój urlop. Należy wpisać ostatni dzień, kiedy jeszcze będziesz przybywać na urlopie.",
    ua: "Вкажіть дату закінчення відпустки. Це повинен бути останній день, коли ви все ще будете перебувати у відпустці.",
    en: "Write the date when your leave will end. You should write the last day you will still be on leave.",
    ru: "Укажите дату окончания отпуска. Это должен быть последний день, когда вы все еще будете пребывать в отпуске.",
  },
  "leave-step-days-count": {
    pl: "Wpisz ilość roboczych dni które obejmuje twój urlop. Nie wliczaj dni wolnych od pracy.",
    ua: "Вкажіть кількість робочих днів, які покриває ваша відпустка. Не враховуйте вихідні дні.",
    en: "Write the number of working days that your leave covers. Do not include holidays.",
    ru: "Укажите количество рабочих дней, которые покрывает ваш отпуск. Не учитывайте выходные дни.",
  },
  "leave-step-signature": {
    pl: "Podpisz wniosek w prawym dolnym rogu. Nie wymaga się podpisu czytelnego.",
    ua: "Поставте свій підпис у правому нижньому куті заяви.",
    en: "Sign the request in the bottom right-hand corner.",
    ru: "Подпишите заявление в правом нижнем углу.",
  },
  "leave-step-manager": {
    pl: "Zanieś wniosek do podpisania do swojego przełożonego.",
    ua: "Передайте заяву на підпис вашому керівнику/лідеру.",
    en: "Take the request to your manager/leader for signature.",
    ru: "Отнесите заявление на подпись своему руководителю/лидеру.",
  },
  "step-1": {
    pl: "Krok 1.",
    ua: "Крок 1.",
    en: "Step 1.",
    ru: "Шаг 1.",
  },
  "step-2": {
    pl: "Krok 2.",
    ua: "Крок 2.",
    en: "Step 2.",
    ru: "Шаг 2.",
  },
  "step-3": {
    pl: "Krok 3.",
    ua: "Крок 3.",
    en: "Step 3.",
    ru: "Шаг 3.",
  },
  "step-4": {
    pl: "Krok 4.",
    ua: "Крок 4.",
    en: "Step 4.",
    ru: "Шаг 4.",
  },
  "step-5": {
    pl: "Krok 5.",
    ua: "Крок 5.",
    en: "Step 5.",
    ru: "Шаг 5.",
  },
  "step-6": {
    pl: "Krok 6.",
    ua: "Крок 6.",
    en: "Step 6.",
    ru: "Шаг 6.",
  },
  "step-7": {
    pl: "Krok 7.",
    ua: "Крок 7.",
    en: "Step 7.",
    ru: "Шаг 7.",
  },
  "step-8": {
    pl: "Krok 8.",
    ua: "Крок 8.",
    en: "Step 8.",
    ru: "Шаг 8.",
  },
  "step-9": {
    pl: "Krok 9.",
    ua: "Крок 9.",
    en: "Step 9.",
    ru: "Шаг 9.",
  },
  "step-10": {
    pl: "Krok 10.",
    ua: "Крок 10.",
    en: "Step 10.",
    ru: "Шаг 10.",
  },
  "step-11": {
    pl: "Krok 11.",
    ua: "Крок 11.",
    en: "Step 11.",
    ru: "Шаг 11.",
  },
  "step-12": {
    pl: "Krok 12.",
    ua: "Крок 12.",
    en: "Step 12.",
    ru: "Шаг 12.",
  },
};
