const lngArr = {
    "homepage" : {
        "pl": "Strona główna",
        "ua": "Головна сторінка",
        "en": "Homepage",
        "ru": "Домашняя страница",
    },
    "about" : {
        "pl": "O aplikacji",
        "ua": "Про додаток",
        "en": "About the application",
        "ru": "О приложении",
    },
    "desc-banner" : {
        "pl": "Centrum informacji dla pracowników AUTODOC",
        "ua": "Інформаційний центр для працівників AUTODOC",
        "en": "AUTODOC employee information center",
        "ru": "Информационный центр для сотрудников AUTODOC",
    },
    "hr-category" : {
        "pl": "Kadry",
        "ua": "Кадри",
        "en": "HR",
        "ru": "Кадры",
    },
    "contacts-category" : {
        "pl": "Kontakty",
        "ua": "Контакти",
        "en": "Contacts",
        "ru": "Контакты",
    },
    "regulations-category" : {
        "pl": "Regulaminy",
        "ua": "Положення",
        "en": "Regulations",
        "ru": "Акты",
    },
    "assist-msg-index" : {
        "pl": "Wybierz kategorię",
        "ua": "Оберіть категорію",
        "en": "Choose a category",
        "ru": "Выберите категорию",
    },
    "work-reg" : {
        "pl": "Regulamin pracy",
        "ua": "Робочий регламент",
        "en": "Work regulations",
        "ru": "Рабочий регламент",
    },
    "bon-reg" : {
        "pl": "Regulamin premii",
        "ua": "Регламент бонусу",
        "en": "Bonus regulations",
        "ru": "Регламент бонуса",
    },
    "applications" : {
        "pl": "Wnioski",
        "ua": "Заяви",
        "en": "Applications",
        "ru": "Заявления",
    },
    "residence" : {
        "pl": "Karta pobytu",
        "ua": "Посвідка на проживання",
        "en": "Residence card",
        "ru": "Вид на жительство",
    },
    "leave-requests" : {
        "pl": "Wnioski o urlop",
        "ua": "Заяви про відпустку",
        "en": "Vacation requests",
        "ru": "Заявления на отпуск",
    },
    "personal-exit" : {
        "pl": "Wyjście prywatne",
        "ua": "Приватний вихід",
        "en": "Private exit",
        "ru": "Частный выход",
    },
    "force-majeure" : {
        "pl": "Siła wyższa",
        "ua": "Форс-мажор",
        "en": "Force majeure",
        "ru": "Форс-мажор",
    },
    "birthday-leave" : {
        "pl": "Urlop urodzinowy",
        "ua": "Вихідний до дня народження",
        "en": "Birthday leave",
        "ru": "Выходной к дню рождения",
    },
    "caring-leave" : {
        "pl": "Urlop opiekuńczy",
        "ua": "Відпустка для догляду",
        "en": "Caregiving leave",
        "ru": "Отпуск по уходу",
    },
    "vacation-cancellation" : {
        "pl": "Anulowanie urlopu",
        "ua": "Скасування відпустки",
        "en": "Vacation cancellation",
        "ru": "Аннулирование отпуска",
    },
};